# 方便复制替换
  dataWorkerMultiaddrs: 
    - /ip4/x.x.x.x/tcp/40000
    - /ip4/x.x.x.x/tcp/40001
    - /ip4/x.x.x.x/tcp/40002
    - /ip4/x.x.x.x/tcp/40003
    - /ip4/x.x.x.x/tcp/40004
    - /ip4/x.x.x.x/tcp/40005
    - /ip4/x.x.x.x/tcp/40006
    - /ip4/x.x.x.x/tcp/40007
    - /ip4/x.x.x.x/tcp/40008
    - /ip4/x.x.x.x/tcp/40009
    - /ip4/x.x.x.x/tcp/40010
    - /ip4/x.x.x.x/tcp/40011
    - /ip4/x.x.x.x/tcp/40012
    - /ip4/x.x.x.x/tcp/40013
    - /ip4/x.x.x.x/tcp/40014
    - /ip4/x.x.x.x/tcp/40015
    - /ip4/x.x.x.x/tcp/40016
    - /ip4/x.x.x.x/tcp/40017
    - /ip4/x.x.x.x/tcp/40018
    - /ip4/x.x.x.x/tcp/40019
    - /ip4/x.x.x.x/tcp/40020
    - /ip4/x.x.x.x/tcp/40021
    - /ip4/x.x.x.x/tcp/40022
    - /ip4/x.x.x.x/tcp/40023
    - /ip4/x.x.x.x/tcp/40024
    - /ip4/x.x.x.x/tcp/40025
    - /ip4/x.x.x.x/tcp/40026
    - /ip4/x.x.x.x/tcp/40027
    - /ip4/x.x.x.x/tcp/40028
    - /ip4/x.x.x.x/tcp/40029
    - /ip4/x.x.x.x/tcp/40030
    - /ip4/x.x.x.x/tcp/40031
    - /ip4/x.x.x.x/tcp/40032
    - /ip4/x.x.x.x/tcp/40033
    - /ip4/x.x.x.x/tcp/40034
    - /ip4/x.x.x.x/tcp/40035
    - /ip4/x.x.x.x/tcp/40036
    - /ip4/x.x.x.x/tcp/40037
    - /ip4/x.x.x.x/tcp/40038
    - /ip4/x.x.x.x/tcp/40039
    - /ip4/x.x.x.x/tcp/40040
    - /ip4/x.x.x.x/tcp/40041
    - /ip4/x.x.x.x/tcp/40042
    - /ip4/x.x.x.x/tcp/40043
    - /ip4/x.x.x.x/tcp/40044
    - /ip4/x.x.x.x/tcp/40045
    - /ip4/x.x.x.x/tcp/40046
    - /ip4/x.x.x.x/tcp/40047
    - /ip4/x.x.x.x/tcp/40048
    - /ip4/x.x.x.x/tcp/40049
    - /ip4/x.x.x.x/tcp/40050
    - /ip4/x.x.x.x/tcp/40051
    - /ip4/x.x.x.x/tcp/40052
    - /ip4/x.x.x.x/tcp/40053
    - /ip4/x.x.x.x/tcp/40054
    - /ip4/x.x.x.x/tcp/40055
    - /ip4/x.x.x.x/tcp/40056
    - /ip4/x.x.x.x/tcp/40057
    - /ip4/x.x.x.x/tcp/40058
    - /ip4/x.x.x.x/tcp/40059
    - /ip4/x.x.x.x/tcp/40060
    - /ip4/x.x.x.x/tcp/40061
    - /ip4/x.x.x.x/tcp/40062
    - /ip4/x.x.x.x/tcp/40063
    - /ip4/x.x.x.x/tcp/40064
    - /ip4/x.x.x.x/tcp/40065
    - /ip4/x.x.x.x/tcp/40066
    - /ip4/x.x.x.x/tcp/40067
    - /ip4/x.x.x.x/tcp/40068
    - /ip4/x.x.x.x/tcp/40069
    - /ip4/x.x.x.x/tcp/40070
    - /ip4/x.x.x.x/tcp/40071
    - /ip4/x.x.x.x/tcp/40072
    - /ip4/x.x.x.x/tcp/40073
    - /ip4/x.x.x.x/tcp/40074
    - /ip4/x.x.x.x/tcp/40075
    - /ip4/x.x.x.x/tcp/40076
    - /ip4/x.x.x.x/tcp/40077
    - /ip4/x.x.x.x/tcp/40078
    - /ip4/x.x.x.x/tcp/40079
    - /ip4/x.x.x.x/tcp/40080
    - /ip4/x.x.x.x/tcp/40081
    - /ip4/x.x.x.x/tcp/40082
    - /ip4/x.x.x.x/tcp/40083
    - /ip4/x.x.x.x/tcp/40084
    - /ip4/x.x.x.x/tcp/40085
    - /ip4/x.x.x.x/tcp/40086
    - /ip4/x.x.x.x/tcp/40087
    - /ip4/x.x.x.x/tcp/40088
    - /ip4/x.x.x.x/tcp/40089
    - /ip4/x.x.x.x/tcp/40090
    - /ip4/x.x.x.x/tcp/40091
    - /ip4/x.x.x.x/tcp/40092
    - /ip4/x.x.x.x/tcp/40093
    - /ip4/x.x.x.x/tcp/40094
    - /ip4/x.x.x.x/tcp/40095
    - /ip4/x.x.x.x/tcp/40096
    - /ip4/x.x.x.x/tcp/40097
    - /ip4/x.x.x.x/tcp/40098
    - /ip4/x.x.x.x/tcp/40099
    - /ip4/x.x.x.x/tcp/40100
    - /ip4/x.x.x.x/tcp/40101
    - /ip4/x.x.x.x/tcp/40102
    - /ip4/x.x.x.x/tcp/40103
    - /ip4/x.x.x.x/tcp/40104
    - /ip4/x.x.x.x/tcp/40105
    - /ip4/x.x.x.x/tcp/40106
    - /ip4/x.x.x.x/tcp/40107
    - /ip4/x.x.x.x/tcp/40108
    - /ip4/x.x.x.x/tcp/40109
    - /ip4/x.x.x.x/tcp/40110
    - /ip4/x.x.x.x/tcp/40111
    - /ip4/x.x.x.x/tcp/40112
    - /ip4/x.x.x.x/tcp/40113
    - /ip4/x.x.x.x/tcp/40114
    - /ip4/x.x.x.x/tcp/40115
    - /ip4/x.x.x.x/tcp/40116
    - /ip4/x.x.x.x/tcp/40117
    - /ip4/x.x.x.x/tcp/40118
    - /ip4/x.x.x.x/tcp/40119
    - /ip4/x.x.x.x/tcp/40120
    - /ip4/x.x.x.x/tcp/40121
    - /ip4/x.x.x.x/tcp/40122
    - /ip4/x.x.x.x/tcp/40123
    - /ip4/x.x.x.x/tcp/40124
    - /ip4/x.x.x.x/tcp/40125
    - /ip4/x.x.x.x/tcp/40126
    - /ip4/x.x.x.x/tcp/40127
    - /ip4/x.x.x.x/tcp/40128
    - /ip4/x.x.x.x/tcp/40129
    - /ip4/x.x.x.x/tcp/40130
    - /ip4/x.x.x.x/tcp/40131
    - /ip4/x.x.x.x/tcp/40132
    - /ip4/x.x.x.x/tcp/40133
    - /ip4/x.x.x.x/tcp/40134
    - /ip4/x.x.x.x/tcp/40135
    - /ip4/x.x.x.x/tcp/40136
    - /ip4/x.x.x.x/tcp/40137
    - /ip4/x.x.x.x/tcp/40138
    - /ip4/x.x.x.x/tcp/40139
    - /ip4/x.x.x.x/tcp/40140
    - /ip4/x.x.x.x/tcp/40141
    - /ip4/x.x.x.x/tcp/40142
    - /ip4/x.x.x.x/tcp/40143
    - /ip4/x.x.x.x/tcp/40144
    - /ip4/x.x.x.x/tcp/40145
    - /ip4/x.x.x.x/tcp/40146
    - /ip4/x.x.x.x/tcp/40147
    - /ip4/x.x.x.x/tcp/40148
    - /ip4/x.x.x.x/tcp/40149
    - /ip4/x.x.x.x/tcp/40150
    - /ip4/x.x.x.x/tcp/40151
    - /ip4/x.x.x.x/tcp/40152
    - /ip4/x.x.x.x/tcp/40153
    - /ip4/x.x.x.x/tcp/40154
    - /ip4/x.x.x.x/tcp/40155
    - /ip4/x.x.x.x/tcp/40156
    - /ip4/x.x.x.x/tcp/40157
    - /ip4/x.x.x.x/tcp/40158
    - /ip4/x.x.x.x/tcp/40159
    - /ip4/x.x.x.x/tcp/40160
    - /ip4/x.x.x.x/tcp/40161
    - /ip4/x.x.x.x/tcp/40162
    - /ip4/x.x.x.x/tcp/40163
    - /ip4/x.x.x.x/tcp/40164
    - /ip4/x.x.x.x/tcp/40165
    - /ip4/x.x.x.x/tcp/40166
    - /ip4/x.x.x.x/tcp/40167
    - /ip4/x.x.x.x/tcp/40168
    - /ip4/x.x.x.x/tcp/40169
    - /ip4/x.x.x.x/tcp/40170
    - /ip4/x.x.x.x/tcp/40171
    - /ip4/x.x.x.x/tcp/40172
    - /ip4/x.x.x.x/tcp/40173
    - /ip4/x.x.x.x/tcp/40174
    - /ip4/x.x.x.x/tcp/40175
    - /ip4/x.x.x.x/tcp/40176
    - /ip4/x.x.x.x/tcp/40177
    - /ip4/x.x.x.x/tcp/40178
    - /ip4/x.x.x.x/tcp/40179
    - /ip4/x.x.x.x/tcp/40180
    - /ip4/x.x.x.x/tcp/40181
    - /ip4/x.x.x.x/tcp/40182
    - /ip4/x.x.x.x/tcp/40183
    - /ip4/x.x.x.x/tcp/40184
    - /ip4/x.x.x.x/tcp/40185
    - /ip4/x.x.x.x/tcp/40186
    - /ip4/x.x.x.x/tcp/40187
    - /ip4/x.x.x.x/tcp/40188
    - /ip4/x.x.x.x/tcp/40189
    - /ip4/x.x.x.x/tcp/40190
    - /ip4/x.x.x.x/tcp/40191
    - /ip4/x.x.x.x/tcp/40192
    - /ip4/x.x.x.x/tcp/40193
    - /ip4/x.x.x.x/tcp/40194
    - /ip4/x.x.x.x/tcp/40195
    - /ip4/x.x.x.x/tcp/40196
    - /ip4/x.x.x.x/tcp/40197
    - /ip4/x.x.x.x/tcp/40198
    - /ip4/x.x.x.x/tcp/40199
    - /ip4/x.x.x.x/tcp/40200
    - /ip4/x.x.x.x/tcp/40201
    - /ip4/x.x.x.x/tcp/40202
    - /ip4/x.x.x.x/tcp/40203
    - /ip4/x.x.x.x/tcp/40204
    - /ip4/x.x.x.x/tcp/40205
    - /ip4/x.x.x.x/tcp/40206
    - /ip4/x.x.x.x/tcp/40207
    - /ip4/x.x.x.x/tcp/40208
    - /ip4/x.x.x.x/tcp/40209
    - /ip4/x.x.x.x/tcp/40210
    - /ip4/x.x.x.x/tcp/40211
    - /ip4/x.x.x.x/tcp/40212
    - /ip4/x.x.x.x/tcp/40213
    - /ip4/x.x.x.x/tcp/40214
    - /ip4/x.x.x.x/tcp/40215
    - /ip4/x.x.x.x/tcp/40216
    - /ip4/x.x.x.x/tcp/40217
    - /ip4/x.x.x.x/tcp/40218
    - /ip4/x.x.x.x/tcp/40219
    - /ip4/x.x.x.x/tcp/40220
    - /ip4/x.x.x.x/tcp/40221
    - /ip4/x.x.x.x/tcp/40222
    - /ip4/x.x.x.x/tcp/40223
    - /ip4/x.x.x.x/tcp/40224
    - /ip4/x.x.x.x/tcp/40225
    - /ip4/x.x.x.x/tcp/40226
    - /ip4/x.x.x.x/tcp/40227
    - /ip4/x.x.x.x/tcp/40228
    - /ip4/x.x.x.x/tcp/40229
    - /ip4/x.x.x.x/tcp/40230
    - /ip4/x.x.x.x/tcp/40231
    - /ip4/x.x.x.x/tcp/40232
    - /ip4/x.x.x.x/tcp/40233
    - /ip4/x.x.x.x/tcp/40234
    - /ip4/x.x.x.x/tcp/40235
    - /ip4/x.x.x.x/tcp/40236
    - /ip4/x.x.x.x/tcp/40237
    - /ip4/x.x.x.x/tcp/40238
    - /ip4/x.x.x.x/tcp/40239
    - /ip4/x.x.x.x/tcp/40240
    - /ip4/x.x.x.x/tcp/40241
    - /ip4/x.x.x.x/tcp/40242
    - /ip4/x.x.x.x/tcp/40243
    - /ip4/x.x.x.x/tcp/40244
    - /ip4/x.x.x.x/tcp/40245
    - /ip4/x.x.x.x/tcp/40246
    - /ip4/x.x.x.x/tcp/40247
    - /ip4/x.x.x.x/tcp/40248
    - /ip4/x.x.x.x/tcp/40249
    - /ip4/x.x.x.x/tcp/40250
    - /ip4/x.x.x.x/tcp/40251
    - /ip4/x.x.x.x/tcp/40252
    - /ip4/x.x.x.x/tcp/40253
    - /ip4/x.x.x.x/tcp/40254
